name: Publish gem

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1.0.0
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
