name: Run tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.1'
      - name: Build and run tests
        run: |
          gem install bundler
          bundle update --conservative --jobs 4 --retry 3
          bundle exec rake spec